[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*

[OUTPUT]
    Name  es
    Match *
    Host  elasticsearch
    Port  9200
    Index docker-logs
